package AppPackage;


import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author home
 */
public class ManageTeachers extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form ManageTeachers
     */
    public ManageTeachers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel72 = new javax.swing.JLabel();
        combo_classTeachers = new javax.swing.JComboBox();
        jLabel76 = new javax.swing.JLabel();
        combo_subjectTeachers = new javax.swing.JComboBox();
        btn_showTeachers = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_subTeachers = new javax.swing.JTextArea();
        btn_saveTeachers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Teachers");
        setIconImage(Toolkit.getDefaultToolkit().getImage("icon\\task.png"));
        setResizable(false);

        jLabel72.setText("Form");

        combo_classTeachers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jLabel76.setText("Subject");

        combo_subjectTeachers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "english", "kiswahili", "physics", "chemistry", "geography", "maths", "biology", "agriculture", "histroy", "buisness_studies", "cre" }));

        btn_showTeachers.setBackground(new java.awt.Color(255, 209, 43));
        btn_showTeachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/class.png"))); // NOI18N
        btn_showTeachers.setText("Show Teachers");
        btn_showTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showTeachersActionPerformed(evt);
            }
        });

        txt_subTeachers.setColumns(20);
        txt_subTeachers.setRows(5);
        jScrollPane1.setViewportView(txt_subTeachers);

        btn_saveTeachers.setBackground(new java.awt.Color(43, 255, 46));
        btn_saveTeachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/saveEdit.png"))); // NOI18N
        btn_saveTeachers.setText("Save");
        btn_saveTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveTeachersActionPerformed(evt);
            }
        });

        jLabel1.setText("Insert / Edit Teachers names");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_classTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_subjectTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_showTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_saveTeachers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(229, 229, 229))
                    .addComponent(jScrollPane1))
                .addGap(16, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(combo_classTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_subjectTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76)
                    .addComponent(btn_showTeachers))
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_saveTeachers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(433, 284));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showTeachersActionPerformed
        // TODO add your handling code here:
        try{
            conn=connect.ConnecrDb();
            String subject = combo_subjectTeachers.getSelectedItem().toString();
            
            String sql = "select "+subject+" from teachers where class=? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, combo_classTeachers.getSelectedItem().toString());
            rs = pst.executeQuery();

            if(rs.next()){
                String add1 = rs.getString(subject);
                txt_subTeachers.setText(add1);               
            }

        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }finally {
            try {
                rs.close();
                conn.close();
                pst.close();
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btn_showTeachersActionPerformed

    private void btn_saveTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveTeachersActionPerformed
        //save teahcer to subject info to system
        try{                    
               conn=connect.ConnecrDb();     
               String subject = combo_subjectTeachers.getSelectedItem().toString();
               
                    String sql = "update teachers set "+subject+" =? where class=? ";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1, txt_subTeachers.getText());
                    pst.setString(2, combo_classTeachers.getSelectedItem().toString());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Teachers information saved!.","Information",JOptionPane.INFORMATION_MESSAGE);
                      
        }catch(HeadlessException | ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }finally {
            try {
                rs.close();
                conn.close();
                pst.close();
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btn_saveTeachersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTeachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_saveTeachers;
    private javax.swing.JButton btn_showTeachers;
    private javax.swing.JComboBox combo_classTeachers;
    private javax.swing.JComboBox combo_subjectTeachers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_subTeachers;
    // End of variables declaration//GEN-END:variables
}
